# Generated by Django 4.2.29 on 2026-03-14 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('journals', '0008_remove_journal_journals_jo_publish_03f116_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(help_text='The publisher this user can manage', on_delete=django.db.models.deletion.CASCADE, related_name='portal_users', to='journals.publisher')),
                ('user', models.OneToOneField(help_text='The user account that has portal access', on_delete=django.db.models.deletion.CASCADE, related_name='publisher_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publisher User',
                'verbose_name_plural': 'Publisher Users',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='Primary key of the changed object')),
                ('object_repr', models.CharField(help_text='String representation of the object at time of change', max_length=255)),
                ('action', models.CharField(choices=[('update', 'Field updated'), ('m2m_add', 'Item added'), ('m2m_remove', 'Item removed')], help_text='Type of change', max_length=20)),
                ('field', models.CharField(help_text='Field or relation that was changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (for field updates)')),
                ('new_value', models.TextField(blank=True, help_text='New value (for field updates) or item name (for M2M)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(help_text='Model type of the changed object', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='portal_audi_content_bfa7d4_idx'), models.Index(fields=['user', '-timestamp'], name='portal_audi_user_id_3c89c6_idx')],
            },
        ),
    ]
