# Generated by Django 5.2.12 on 2026-03-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_reversion',
            field=models.BooleanField(default=False, help_text='True when this entry was created by reverting a previous change'),
        ),
    ]
