# Generated by Django 4.2.29 on 2026-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title (translatable)', max_length=255)),
                ('title_en', models.CharField(help_text='Page title (translatable)', max_length=255, null=True)),
                ('title_fr', models.CharField(help_text='Page title (translatable)', max_length=255, null=True)),
                ('title_es', models.CharField(help_text='Page title (translatable)', max_length=255, null=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('body', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)')),
                ('body_en', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True)),
                ('body_fr', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True)),
                ('body_es', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320)),
                ('meta_description_en', models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320, null=True)),
                ('meta_description_fr', models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320, null=True)),
                ('meta_description_es', models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Only published pages are visible on the site')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label (translatable)', max_length=255)),
                ('name_en', models.CharField(help_text='Human-readable label (translatable)', max_length=255, null=True)),
                ('name_fr', models.CharField(help_text='Human-readable label (translatable)', max_length=255, null=True)),
                ('name_es', models.CharField(help_text='Human-readable label (translatable)', max_length=255, null=True)),
                ('key', models.SlugField(help_text='Unique lookup key used in templates', max_length=100, unique=True)),
                ('body', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)')),
                ('body_en', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True)),
                ('body_fr', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True)),
                ('body_es', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
                'ordering': ['name'],
            },
        ),
    ]
