# Generated by Django 4.2.29 on 2026-03-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title (translatable)', max_length=255)),
                ('title_en', models.CharField(help_text='Post title (translatable)', max_length=255, null=True)),
                ('title_fr', models.CharField(help_text='Post title (translatable)', max_length=255, null=True)),
                ('title_es', models.CharField(help_text='Post title (translatable)', max_length=255, null=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short summary shown in listings (translatable)')),
                ('summary_en', models.TextField(blank=True, help_text='Short summary shown in listings (translatable)', null=True)),
                ('summary_fr', models.TextField(blank=True, help_text='Short summary shown in listings (translatable)', null=True)),
                ('summary_es', models.TextField(blank=True, help_text='Short summary shown in listings (translatable)', null=True)),
                ('body', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)')),
                ('body_en', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True)),
                ('body_fr', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True)),
                ('body_es', models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320)),
                ('meta_description_en', models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320, null=True)),
                ('meta_description_fr', models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320, null=True)),
                ('meta_description_es', models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Only published posts are visible on the site')),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date; used for ordering in listings', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_published'], name='cms_post_publish_c185c9_idx')],
            },
        ),
    ]
