# Generated by Django 4.2.29 on 2026-03-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_post'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='cms_post_publish_c185c9_idx',
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_published', 'sort_order', 'title'], name='cms_page_is_publ_f38a87_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-published_at'], name='cms_post_is_publ_2c8d8b_idx'),
        ),
    ]
