# Generated by Django 4.2.29 on 2026-03-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_post_cms_post_publish_c185c9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='body_de',
            field=models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_de',
            field=models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_de',
            field=models.CharField(help_text='Page title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_de',
            field=models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_de',
            field=models.CharField(blank=True, help_text='SEO meta description (translatable)', max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_de',
            field=models.TextField(blank=True, help_text='Short summary shown in listings (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_de',
            field=models.CharField(help_text='Post title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='body_de',
            field=models.TextField(blank=True, help_text='Rich-text HTML content (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='name_de',
            field=models.CharField(help_text='Human-readable label (translatable)', max_length=255, null=True),
        ),
    ]
