# Generated by Django 5.2.12 on 2026-03-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_seed_landing_page_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='byline',
            field=models.CharField(blank=True, help_text="Author name displayed on the post. Defaults to the creating user's name.", max_length=255),
        ),
    ]
