# Generated by Django 5.2.12 on 2026-03-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_seed_landing_page_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline_1', models.CharField(default='For Academics.', help_text='First tagline (translatable)', max_length=255)),
                ('tagline_1_en', models.CharField(default='For Academics.', help_text='First tagline (translatable)', max_length=255, null=True)),
                ('tagline_1_fr', models.CharField(default='For Academics.', help_text='First tagline (translatable)', max_length=255, null=True)),
                ('tagline_1_de', models.CharField(default='For Academics.', help_text='First tagline (translatable)', max_length=255, null=True)),
                ('tagline_1_es', models.CharField(default='For Academics.', help_text='First tagline (translatable)', max_length=255, null=True)),
                ('tagline_2', models.CharField(default='For Libraries.', help_text='Second tagline (translatable)', max_length=255)),
                ('tagline_2_en', models.CharField(default='For Libraries.', help_text='Second tagline (translatable)', max_length=255, null=True)),
                ('tagline_2_fr', models.CharField(default='For Libraries.', help_text='Second tagline (translatable)', max_length=255, null=True)),
                ('tagline_2_de', models.CharField(default='For Libraries.', help_text='Second tagline (translatable)', max_length=255, null=True)),
                ('tagline_2_es', models.CharField(default='For Libraries.', help_text='Second tagline (translatable)', max_length=255, null=True)),
                ('tagline_3', models.CharField(default='For Publishers.', help_text='Third tagline (translatable)', max_length=255)),
                ('tagline_3_en', models.CharField(default='For Publishers.', help_text='Third tagline (translatable)', max_length=255, null=True)),
                ('tagline_3_fr', models.CharField(default='For Publishers.', help_text='Third tagline (translatable)', max_length=255, null=True)),
                ('tagline_3_de', models.CharField(default='For Publishers.', help_text='Third tagline (translatable)', max_length=255, null=True)),
                ('tagline_3_es', models.CharField(default='For Publishers.', help_text='Third tagline (translatable)', max_length=255, null=True)),
                ('column_1_heading', models.CharField(default='About OJC', help_text='Column 1 heading (translatable)', max_length=255)),
                ('column_1_heading_en', models.CharField(default='About OJC', help_text='Column 1 heading (translatable)', max_length=255, null=True)),
                ('column_1_heading_fr', models.CharField(default='About OJC', help_text='Column 1 heading (translatable)', max_length=255, null=True)),
                ('column_1_heading_de', models.CharField(default='About OJC', help_text='Column 1 heading (translatable)', max_length=255, null=True)),
                ('column_1_heading_es', models.CharField(default='About OJC', help_text='Column 1 heading (translatable)', max_length=255, null=True)),
                ('column_2_heading', models.CharField(default='Contact us', help_text='Column 2 heading (translatable)', max_length=255)),
                ('column_2_heading_en', models.CharField(default='Contact us', help_text='Column 2 heading (translatable)', max_length=255, null=True)),
                ('column_2_heading_fr', models.CharField(default='Contact us', help_text='Column 2 heading (translatable)', max_length=255, null=True)),
                ('column_2_heading_de', models.CharField(default='Contact us', help_text='Column 2 heading (translatable)', max_length=255, null=True)),
                ('column_2_heading_es', models.CharField(default='Contact us', help_text='Column 2 heading (translatable)', max_length=255, null=True)),
                ('legal_text', models.TextField(blank=True, help_text='Legal text (rich text, translatable)')),
                ('legal_text_en', models.TextField(blank=True, help_text='Legal text (rich text, translatable)', null=True)),
                ('legal_text_fr', models.TextField(blank=True, help_text='Legal text (rich text, translatable)', null=True)),
                ('legal_text_de', models.TextField(blank=True, help_text='Legal text (rich text, translatable)', null=True)),
                ('legal_text_es', models.TextField(blank=True, help_text='Legal text (rich text, translatable)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.PositiveIntegerField(choices=[(1, 'Column 1'), (2, 'Column 2')])),
                ('label', models.CharField(help_text='Link label (translatable)', max_length=255)),
                ('label_en', models.CharField(help_text='Link label (translatable)', max_length=255, null=True)),
                ('label_fr', models.CharField(help_text='Link label (translatable)', max_length=255, null=True)),
                ('label_de', models.CharField(help_text='Link label (translatable)', max_length=255, null=True)),
                ('label_es', models.CharField(help_text='Link label (translatable)', max_length=255, null=True)),
                ('url', models.CharField(blank=True, help_text='Link URL', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.footersettings')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
