# Generated by Django 5.2.12 on 2026-03-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_post_byline'),
        ('cms', '0008_seed_footer_defaults'),
    ]

    operations = [
    ]
