# Generated by Django 5.2.12 on 2026-03-15 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_seed_footer_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_line_1', models.CharField(default='Open', help_text='Logo text line 1 (translatable)', max_length=100)),
                ('logo_line_1_en', models.CharField(default='Open', help_text='Logo text line 1 (translatable)', max_length=100, null=True)),
                ('logo_line_1_fr', models.CharField(default='Open', help_text='Logo text line 1 (translatable)', max_length=100, null=True)),
                ('logo_line_1_de', models.CharField(default='Open', help_text='Logo text line 1 (translatable)', max_length=100, null=True)),
                ('logo_line_1_es', models.CharField(default='Open', help_text='Logo text line 1 (translatable)', max_length=100, null=True)),
                ('logo_line_2', models.CharField(default='Journals', help_text='Logo text line 2 (translatable)', max_length=100)),
                ('logo_line_2_en', models.CharField(default='Journals', help_text='Logo text line 2 (translatable)', max_length=100, null=True)),
                ('logo_line_2_fr', models.CharField(default='Journals', help_text='Logo text line 2 (translatable)', max_length=100, null=True)),
                ('logo_line_2_de', models.CharField(default='Journals', help_text='Logo text line 2 (translatable)', max_length=100, null=True)),
                ('logo_line_2_es', models.CharField(default='Journals', help_text='Logo text line 2 (translatable)', max_length=100, null=True)),
                ('logo_line_3', models.CharField(default='Collective', help_text='Logo text line 3 (translatable)', max_length=100)),
                ('logo_line_3_en', models.CharField(default='Collective', help_text='Logo text line 3 (translatable)', max_length=100, null=True)),
                ('logo_line_3_fr', models.CharField(default='Collective', help_text='Logo text line 3 (translatable)', max_length=100, null=True)),
                ('logo_line_3_de', models.CharField(default='Collective', help_text='Logo text line 3 (translatable)', max_length=100, null=True)),
                ('logo_line_3_es', models.CharField(default='Collective', help_text='Logo text line 3 (translatable)', max_length=100, null=True)),
                ('cta_label', models.CharField(default='GET INVOLVED', help_text='CTA button label (translatable)', max_length=100)),
                ('cta_label_en', models.CharField(default='GET INVOLVED', help_text='CTA button label (translatable)', max_length=100, null=True)),
                ('cta_label_fr', models.CharField(default='GET INVOLVED', help_text='CTA button label (translatable)', max_length=100, null=True)),
                ('cta_label_de', models.CharField(default='GET INVOLVED', help_text='CTA button label (translatable)', max_length=100, null=True)),
                ('cta_label_es', models.CharField(default='GET INVOLVED', help_text='CTA button label (translatable)', max_length=100, null=True)),
                ('cta_url', models.CharField(default='mailto:info@openjournalscollective.org?subject=Open Journals Collective', help_text='CTA button URL', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header Settings',
                'verbose_name_plural': 'Header Settings',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Menu item label (translatable)', max_length=255)),
                ('label_en', models.CharField(help_text='Menu item label (translatable)', max_length=255, null=True)),
                ('label_fr', models.CharField(help_text='Menu item label (translatable)', max_length=255, null=True)),
                ('label_de', models.CharField(help_text='Menu item label (translatable)', max_length=255, null=True)),
                ('label_es', models.CharField(help_text='Menu item label (translatable)', max_length=255, null=True)),
                ('url', models.CharField(blank=True, help_text='Menu item URL', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('show_cta_in_dropdown', models.BooleanField(default=False, help_text="Show CTA button in this item's dropdown (top-level only)")),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cms.headersettings')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
