# Generated by Django 5.2.12 on 2026-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_seed_header_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Call-to-action button text (falls back to global if empty, translatable)', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cta_text_de',
            field=models.CharField(blank=True, help_text='Call-to-action button text (falls back to global if empty, translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cta_text_en',
            field=models.CharField(blank=True, help_text='Call-to-action button text (falls back to global if empty, translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cta_text_es',
            field=models.CharField(blank=True, help_text='Call-to-action button text (falls back to global if empty, translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cta_text_fr',
            field=models.CharField(blank=True, help_text='Call-to-action button text (falls back to global if empty, translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Call-to-action button URL (falls back to global if empty)', max_length=500),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='show_cta_in_dropdown',
            field=models.BooleanField(default=False, help_text="Show call-to-action button in this item's dropdown (top-level only)"),
        ),
    ]
