# Generated by Django 5.2.12 on 2026-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_menuitem_cta_text_menuitem_cta_text_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='show_mobile_sub_items',
            field=models.BooleanField(default=True, help_text='Show sub-menu items in the mobile navigation'),
        ),
    ]
