# Generated by Django 5.2.12 on 2026-03-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_merge_0007_add_post_byline_0008_seed_footer_defaults'),
        ('cms', '0012_headersettings_show_mobile_sub_items'),
    ]

    operations = [
    ]
