# Generated by Django 5.2.12 on 2026-03-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_add_preview_token'),
        ('cms', '0013_merge_20260315_1602'),
    ]

    operations = [
    ]
