# Generated by Django 5.2.12 on 2026-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_merge_0010_add_preview_token_0013_merge_20260315_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_arc_position',
            field=models.CharField(choices=[('top-right', 'Top right'), ('top-left', 'Top left'), ('bottom-right', 'Bottom right'), ('bottom-left', 'Bottom left'), ('none', 'None')], default='top-right', help_text='Position of the decorative arc in the hero section', max_length=14),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_bg',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('dark', 'Dark'), ('white', 'White')], default='yellow', help_text='Hero section background colour', max_length=10),
        ),
    ]
