# Generated by Django 5.2.12 on 2026-03-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_add_page_hero_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='hero_arc_position',
            field=models.CharField(choices=[('top-right', 'Top right'), ('top-left', 'Top left'), ('center-right', 'Centre right'), ('center-left', 'Centre left'), ('bottom-right', 'Bottom right'), ('bottom-left', 'Bottom left'), ('none', 'None')], default='top-right', help_text='Position of the decorative arc in the hero section', max_length=14),
        ),
    ]
