# Generated by Django 5.2.12 on 2026-03-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_add_center_arc_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.CharField(blank=True, help_text='Featured image URL — uploaded via the manager', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='cms.category'),
        ),
    ]
