# Generated by Django 5.2.12 on 2026-03-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_add_center_arc_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurModelPackageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Table title (translatable)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Table description (translatable)')),
                ('colour_preset', models.CharField(choices=[('pink', 'Pink'), ('green', 'Green'), ('blue', 'Blue'), ('custom', 'Custom')], default='pink', max_length=10)),
                ('custom_header_bg', models.CharField(blank=True, help_text='Hex colour for header (custom only)', max_length=7)),
                ('custom_row_bg', models.CharField(blank=True, help_text='Hex colour for rows (custom only)', max_length=7)),
                ('custom_text_colour', models.CharField(blank=True, help_text='Hex colour for text (custom only)', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OurModelPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='our-model', help_text='URL slug for the page')),
                ('hero_heading', models.TextField(help_text="Main hero heading — may contain <span class='highlight'> markup (translatable)")),
                ('hero_image_alt', models.CharField(default='', help_text='Alt text for the hero image (translatable)', max_length=255)),
                ('model_heading', models.CharField(help_text='OJC Model section heading (translatable)', max_length=255)),
                ('model_body', models.TextField(blank=True, help_text='OJC Model section body — rich text (translatable)')),
                ('collections_label', models.TextField(blank=True, help_text='Label above collection cards (translatable)')),
                ('collection_1_number', models.CharField(default='01', max_length=10)),
                ('collection_1_title', models.CharField(help_text='Collection 1 title (translatable)', max_length=255)),
                ('collection_1_link_text', models.CharField(default='BROWSE JOURNALS', help_text='Collection 1 link label (translatable)', max_length=100)),
                ('collection_1_link_url', models.CharField(blank=True, max_length=500)),
                ('collection_2_number', models.CharField(default='02', max_length=10)),
                ('collection_2_title', models.CharField(help_text='Collection 2 title (translatable)', max_length=255)),
                ('collection_2_link_text', models.CharField(default='BROWSE JOURNALS', help_text='Collection 2 link label (translatable)', max_length=100)),
                ('collection_2_link_url', models.CharField(blank=True, max_length=500)),
                ('collection_3_number', models.CharField(default='03', max_length=10)),
                ('collection_3_title', models.CharField(help_text='Collection 3 title (translatable)', max_length=255)),
                ('collection_3_link_text', models.CharField(default='BROWSE JOURNALS', help_text='Collection 3 link label (translatable)', max_length=100)),
                ('collection_3_link_url', models.CharField(blank=True, max_length=500)),
                ('funding_heading', models.CharField(help_text='Funding section heading (translatable)', max_length=255)),
                ('funding_upper_image_alt', models.CharField(default='', help_text='Alt text for upper funding image (translatable)', max_length=255)),
                ('funding_lower_image_alt', models.CharField(default='', help_text='Alt text for lower funding image (translatable)', max_length=255)),
                ('funding_body', models.TextField(blank=True, help_text='Funding section body — rich text (translatable)')),
                ('revenue_heading', models.CharField(help_text='Revenue distribution heading (translatable)', max_length=255)),
                ('revenue_description', models.TextField(blank=True, help_text='Revenue description — plain text (translatable)')),
                ('revenue_callout', models.TextField(blank=True, help_text='Revenue callout text (translatable)')),
                ('cta_heading', models.CharField(help_text='CTA heading (translatable)', max_length=255)),
                ('cta_description', models.TextField(blank=True, help_text='CTA description — rich text (translatable)')),
                ('cta_button_text', models.CharField(help_text='CTA button label (translatable)', max_length=100)),
                ('cta_button_url', models.CharField(blank=True, max_length=500)),
                ('cta_button_visible', models.BooleanField(default=True)),
                ('cta_image_alt', models.CharField(default='', help_text='Alt text for CTA image (translatable)', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Our Model Page Settings',
                'verbose_name_plural': 'Our Model Page Settings',
            },
        ),
        migrations.CreateModel(
            name='OurModelPackageRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='cms.ourmodelpackagetable')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='ourmodelpackagetable',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_tables', to='cms.ourmodelpagesettings'),
        ),
        migrations.CreateModel(
            name='OurModelTableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Column heading (translatable)', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='cms.ourmodelpagesettings')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OurModelPackageCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='Cell value (translatable)', max_length=255)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='cms.ourmodelpackagerow')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.ourmodeltablecolumn')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('row', 'column'), name='unique_cell_per_row_column')],
            },
        ),
    ]
