# Generated by Django 5.2.12 on 2026-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_ourmodelpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmodelpackagecell',
            name='value_de',
            field=models.CharField(blank=True, help_text='Cell value (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagecell',
            name='value_en',
            field=models.CharField(blank=True, help_text='Cell value (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagecell',
            name='value_es',
            field=models.CharField(blank=True, help_text='Cell value (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagecell',
            name='value_fr',
            field=models.CharField(blank=True, help_text='Cell value (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagetable',
            name='description_de',
            field=models.TextField(blank=True, help_text='Table description (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagetable',
            name='description_en',
            field=models.TextField(blank=True, help_text='Table description (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagetable',
            name='description_es',
            field=models.TextField(blank=True, help_text='Table description (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagetable',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Table description (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagetable',
            name='title_de',
            field=models.CharField(help_text='Table title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagetable',
            name='title_en',
            field=models.CharField(help_text='Table title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagetable',
            name='title_es',
            field=models.CharField(help_text='Table title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpackagetable',
            name='title_fr',
            field=models.CharField(help_text='Table title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_1_link_text_de',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 1 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_1_link_text_en',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 1 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_1_link_text_es',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 1 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_1_link_text_fr',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 1 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_1_title_de',
            field=models.CharField(help_text='Collection 1 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_1_title_en',
            field=models.CharField(help_text='Collection 1 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_1_title_es',
            field=models.CharField(help_text='Collection 1 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_1_title_fr',
            field=models.CharField(help_text='Collection 1 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_2_link_text_de',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 2 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_2_link_text_en',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 2 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_2_link_text_es',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 2 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_2_link_text_fr',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 2 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_2_title_de',
            field=models.CharField(help_text='Collection 2 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_2_title_en',
            field=models.CharField(help_text='Collection 2 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_2_title_es',
            field=models.CharField(help_text='Collection 2 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_2_title_fr',
            field=models.CharField(help_text='Collection 2 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_3_link_text_de',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 3 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_3_link_text_en',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 3 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_3_link_text_es',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 3 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_3_link_text_fr',
            field=models.CharField(default='BROWSE JOURNALS', help_text='Collection 3 link label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_3_title_de',
            field=models.CharField(help_text='Collection 3 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_3_title_en',
            field=models.CharField(help_text='Collection 3 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_3_title_es',
            field=models.CharField(help_text='Collection 3 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collection_3_title_fr',
            field=models.CharField(help_text='Collection 3 title (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collections_label_de',
            field=models.TextField(blank=True, help_text='Label above collection cards (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collections_label_en',
            field=models.TextField(blank=True, help_text='Label above collection cards (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collections_label_es',
            field=models.TextField(blank=True, help_text='Label above collection cards (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='collections_label_fr',
            field=models.TextField(blank=True, help_text='Label above collection cards (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_button_text_de',
            field=models.CharField(help_text='CTA button label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_button_text_en',
            field=models.CharField(help_text='CTA button label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_button_text_es',
            field=models.CharField(help_text='CTA button label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_button_text_fr',
            field=models.CharField(help_text='CTA button label (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_description_de',
            field=models.TextField(blank=True, help_text='CTA description — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_description_en',
            field=models.TextField(blank=True, help_text='CTA description — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_description_es',
            field=models.TextField(blank=True, help_text='CTA description — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_description_fr',
            field=models.TextField(blank=True, help_text='CTA description — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_heading_de',
            field=models.CharField(help_text='CTA heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_heading_en',
            field=models.CharField(help_text='CTA heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_heading_es',
            field=models.CharField(help_text='CTA heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_heading_fr',
            field=models.CharField(help_text='CTA heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_image_alt_de',
            field=models.CharField(default='', help_text='Alt text for CTA image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_image_alt_en',
            field=models.CharField(default='', help_text='Alt text for CTA image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_image_alt_es',
            field=models.CharField(default='', help_text='Alt text for CTA image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='cta_image_alt_fr',
            field=models.CharField(default='', help_text='Alt text for CTA image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_body_de',
            field=models.TextField(blank=True, help_text='Funding section body — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_body_en',
            field=models.TextField(blank=True, help_text='Funding section body — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_body_es',
            field=models.TextField(blank=True, help_text='Funding section body — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_body_fr',
            field=models.TextField(blank=True, help_text='Funding section body — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_heading_de',
            field=models.CharField(help_text='Funding section heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_heading_en',
            field=models.CharField(help_text='Funding section heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_heading_es',
            field=models.CharField(help_text='Funding section heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_heading_fr',
            field=models.CharField(help_text='Funding section heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_lower_image_alt_de',
            field=models.CharField(default='', help_text='Alt text for lower funding image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_lower_image_alt_en',
            field=models.CharField(default='', help_text='Alt text for lower funding image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_lower_image_alt_es',
            field=models.CharField(default='', help_text='Alt text for lower funding image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_lower_image_alt_fr',
            field=models.CharField(default='', help_text='Alt text for lower funding image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_upper_image_alt_de',
            field=models.CharField(default='', help_text='Alt text for upper funding image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_upper_image_alt_en',
            field=models.CharField(default='', help_text='Alt text for upper funding image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_upper_image_alt_es',
            field=models.CharField(default='', help_text='Alt text for upper funding image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='funding_upper_image_alt_fr',
            field=models.CharField(default='', help_text='Alt text for upper funding image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='hero_heading_de',
            field=models.TextField(help_text="Main hero heading — may contain <span class='highlight'> markup (translatable)", null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='hero_heading_en',
            field=models.TextField(help_text="Main hero heading — may contain <span class='highlight'> markup (translatable)", null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='hero_heading_es',
            field=models.TextField(help_text="Main hero heading — may contain <span class='highlight'> markup (translatable)", null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='hero_heading_fr',
            field=models.TextField(help_text="Main hero heading — may contain <span class='highlight'> markup (translatable)", null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='hero_image_alt_de',
            field=models.CharField(default='', help_text='Alt text for the hero image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='hero_image_alt_en',
            field=models.CharField(default='', help_text='Alt text for the hero image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='hero_image_alt_es',
            field=models.CharField(default='', help_text='Alt text for the hero image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='hero_image_alt_fr',
            field=models.CharField(default='', help_text='Alt text for the hero image (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='model_body_de',
            field=models.TextField(blank=True, help_text='OJC Model section body — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='model_body_en',
            field=models.TextField(blank=True, help_text='OJC Model section body — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='model_body_es',
            field=models.TextField(blank=True, help_text='OJC Model section body — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='model_body_fr',
            field=models.TextField(blank=True, help_text='OJC Model section body — rich text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='model_heading_de',
            field=models.CharField(help_text='OJC Model section heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='model_heading_en',
            field=models.CharField(help_text='OJC Model section heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='model_heading_es',
            field=models.CharField(help_text='OJC Model section heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='model_heading_fr',
            field=models.CharField(help_text='OJC Model section heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_callout_de',
            field=models.TextField(blank=True, help_text='Revenue callout text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_callout_en',
            field=models.TextField(blank=True, help_text='Revenue callout text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_callout_es',
            field=models.TextField(blank=True, help_text='Revenue callout text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_callout_fr',
            field=models.TextField(blank=True, help_text='Revenue callout text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_description_de',
            field=models.TextField(blank=True, help_text='Revenue description — plain text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_description_en',
            field=models.TextField(blank=True, help_text='Revenue description — plain text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_description_es',
            field=models.TextField(blank=True, help_text='Revenue description — plain text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_description_fr',
            field=models.TextField(blank=True, help_text='Revenue description — plain text (translatable)', null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_heading_de',
            field=models.CharField(help_text='Revenue distribution heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_heading_en',
            field=models.CharField(help_text='Revenue distribution heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_heading_es',
            field=models.CharField(help_text='Revenue distribution heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodelpagesettings',
            name='revenue_heading_fr',
            field=models.CharField(help_text='Revenue distribution heading (translatable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourmodeltablecolumn',
            name='heading_de',
            field=models.CharField(help_text='Column heading (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodeltablecolumn',
            name='heading_en',
            field=models.CharField(help_text='Column heading (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodeltablecolumn',
            name='heading_es',
            field=models.CharField(help_text='Column heading (translatable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmodeltablecolumn',
            name='heading_fr',
            field=models.CharField(help_text='Column heading (translatable)', max_length=100, null=True),
        ),
    ]
