# Generated by Django 5.2.12 on 2026-03-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_add_category_and_post_featured_image'),
        ('cms', '0019_seed_our_model_defaults'),
    ]

    operations = [
    ]
