# Generated by Django 5.2.12 on 2026-03-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_seed_team_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(default='noreply@example.com', help_text='Sender address for contact form emails', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Form Settings',
                'verbose_name_plural': 'Contact Form Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='cms.contactformsettings')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
