# Generated by Django 5.2.12 on 2026-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_seed_board_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestoPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='our-manifesto', help_text='URL slug for the page')),
                ('hero_heading', models.CharField(default='OJC is leading a growing academic movement.', help_text='Main hero heading', max_length=500)),
                ('hero_sub', models.TextField(blank=True, default='Our mission is to build a sustainable future for academic journals by challenging the profit-making models of global corporate publishing and data systems.', help_text='Hero sub-heading text')),
                ('hero_image_alt', models.CharField(default='A person contemplating the future of academic publishing', help_text='Alt text for the hero image', max_length=255)),
                ('text_body', models.TextField(blank=True, help_text='Main text block — rich text (bold, italic, underline, sub, sup only)')),
                ('organise_heading', models.CharField(default='To do this, we must organise.', help_text='Organise section heading', max_length=500)),
                ('organise_body', models.TextField(blank=True, help_text='Organise section body — rich text')),
                ('achievable_heading', models.CharField(default='Our task is ambitious, yet achievable.', help_text='Achievable section heading', max_length=500)),
                ('achievable_body', models.TextField(blank=True, help_text='Achievable section body — rich text')),
                ('cta_button_text', models.CharField(default='It starts here', help_text='CTA button text', max_length=100)),
                ('cta_button_url', models.CharField(default='/our-team/', help_text='CTA button URL', max_length=500)),
                ('final_heading', models.CharField(default="Free access to hundreds of the world's leading academic journals.", help_text='Final section heading', max_length=500)),
                ('final_image_alt', models.CharField(default='A modern library representing free access to academic journals', help_text='Alt text for the final section image', max_length=255)),
                ('final_button_text', models.CharField(default='Speak to us', help_text='Final section button text', max_length=100)),
                ('final_button_url', models.CharField(default='/our-team/', help_text='Final section button URL', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manifesto Page Settings',
                'verbose_name_plural': 'Manifesto Page Settings',
            },
        ),
    ]
