# Generated by Django 5.2.12

import shutil
from pathlib import Path

from django.conf import settings as django_settings
from django.db import migrations

LOREM = (
    "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam "
    "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat "
    "volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation "
    "ullamcorper. Ut wisi enim ad minim veniam."
)

STAT_TEXT = (
    "Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed diam "
    "nonummy nibh euismod tincidunt. Reasequa a, consequat vita abosrque. "
    "Ut wisi enim ad."
)

HERO_HEADING = (
    "Our mission is lorem ipsum dolor sit amet, consectetur ips remit et."
)

QUOTE_1_TEXT = (
    "Quote from a publisher that\u2019s already onboard. "
    "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, "
    "sed diam nonummy nibh euismod tincidunt ut laoreet."
)

QUOTE_2_TEXT = (
    "The Open Journals Collective provides a community-led, "
    "scalable opportunity for libraries to invest in trusted "
    "open access journals."
)

# Static source → media destination (relative to MEDIA_ROOT)
LOGO_FILES = {
    "mpub-quote-logo.png": "about_us/logos/mpub-quote-logo.png",
    "doaj-quote-logo.svg": "about_us/logos/doaj-quote-logo.svg",
}


def _copy_logos():
    """Copy default logos from static/img/ into MEDIA_ROOT/about_us/logos/."""
    base_dir = Path(django_settings.BASE_DIR)
    media_root = Path(django_settings.MEDIA_ROOT)
    logos_dir = media_root / "about_us" / "logos"
    logos_dir.mkdir(parents=True, exist_ok=True)

    for src_name, dest_rel in LOGO_FILES.items():
        src = base_dir / "static" / "img" / src_name
        dest = media_root / dest_rel
        if src.exists() and not dest.exists():
            shutil.copy2(src, dest)


def populate_defaults(apps, schema_editor):
    AboutUsPageSettings = apps.get_model("cms", "AboutUsPageSettings")
    AboutUsQuote = apps.get_model("cms", "AboutUsQuote")

    _copy_logos()

    col_body = f"<p>{LOREM}</p>"

    settings, _ = AboutUsPageSettings.objects.get_or_create(
        pk=1,
        defaults={
            "slug": "about-us",
            "hero_heading": HERO_HEADING,
            "hero_heading_en": HERO_HEADING,
            "hero_sub": "",
            "hero_sub_en": "",
            "section_title": "About us.",
            "section_title_en": "About us.",
            "col_1_title": "Our vision.",
            "col_1_title_en": "Our vision.",
            "col_1_body": col_body,
            "col_1_body_en": col_body,
            "col_2_title": "Our Mission.",
            "col_2_title_en": "Our Mission.",
            "col_2_body": col_body,
            "col_2_body_en": col_body,
            "stat_1_value": "6",
            "stat_1_value_en": "6",
            "stat_1_text": STAT_TEXT,
            "stat_1_text_en": STAT_TEXT,
            "stat_2_value": "60%",
            "stat_2_value_en": "60%",
            "stat_2_text": STAT_TEXT,
            "stat_2_text_en": STAT_TEXT,
            "stat_3_value": "3m",
            "stat_3_value_en": "3m",
            "stat_3_text": STAT_TEXT,
            "stat_3_text_en": STAT_TEXT,
            "stat_4_value": "300k",
            "stat_4_value_en": "300k",
            "stat_4_text": STAT_TEXT,
            "stat_4_text_en": STAT_TEXT,
        },
    )

    AboutUsQuote.objects.get_or_create(
        page=settings,
        sort_order=1,
        defaults={
            "quote_text": QUOTE_1_TEXT,
            "quote_text_en": QUOTE_1_TEXT,
            "author_name": "Name Here, Company",
            "author_name_en": "Name Here, Company",
            "logo": LOGO_FILES["mpub-quote-logo.png"],
        },
    )

    AboutUsQuote.objects.get_or_create(
        page=settings,
        sort_order=2,
        defaults={
            "quote_text": QUOTE_2_TEXT,
            "quote_text_en": QUOTE_2_TEXT,
            "author_name": "Joanna Ball, Managing Director, DOAJ",
            "author_name_en": "Joanna Ball, Managing Director, DOAJ",
            "logo": LOGO_FILES["doaj-quote-logo.svg"],
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0028_aboutuspagesettings_aboutusquote"),
    ]

    operations = [
        migrations.RunPython(populate_defaults, migrations.RunPython.noop),
    ]
