# Generated by Django 5.2.12 on 2026-03-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_populate_about_us_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMembersPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Our members.', help_text='Main hero heading', max_length=500)),
                ('section_heading', models.CharField(default='Who we are.', help_text='Content section heading', max_length=200)),
                ('circle_1_title', models.CharField(default='We are Academics.', help_text='Circle 1 title', max_length=200)),
                ('circle_1_body', models.TextField(blank=True, help_text='Circle 1 body — rich text, sanitized')),
                ('circle_2_title', models.CharField(default='We are Librarians.', help_text='Circle 2 title', max_length=200)),
                ('circle_2_body', models.TextField(blank=True, help_text='Circle 2 body — rich text, sanitized')),
                ('circle_3_title', models.CharField(default='We are Publishers.', help_text='Circle 3 title', max_length=200)),
                ('circle_3_body', models.TextField(blank=True, help_text='Circle 3 body — rich text, sanitized')),
                ('cta_text', models.CharField(default='Join Us', help_text='Call-to-action button text', max_length=200)),
                ('cta_url', models.CharField(blank=True, default='#', help_text='Call-to-action button URL', max_length=500)),
                ('members_heading', models.CharField(default='OJC Members.', help_text='Members list section heading', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Our Members Page Settings',
                'verbose_name_plural': 'Our Members Page Settings',
            },
        ),
        migrations.CreateModel(
            name='OurMembersBottomQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Quote image', upload_to='our_members/bottom/')),
                ('quote_text', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_quotes', to='cms.ourmemberspagesettings')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OurMemberInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='cms.ourmemberspagesettings')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OurMembersTopQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Quote image', upload_to='our_members/top/')),
                ('quote_text', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_quotes', to='cms.ourmemberspagesettings')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
