# Generated by Django 5.2.12 on 2026-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_populate_our_members_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='show_bottom_carousel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='show_cta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='show_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='show_members_grid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='show_top_carousel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='show_who_we_are',
            field=models.BooleanField(default=True),
        ),
    ]
