# Generated by Django 5.2.12 on 2026-03-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_ourmemberspagesettings_show_bottom_carousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='section_order',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of section keys'),
        ),
    ]
