# Generated by Django 5.2.12 on 2026-03-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_populate_section_order_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourmemberspagesettings',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='ourmemberspagesettings',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='ourmemberspagesettings',
            name='show_cta',
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='members_grid_cta_text',
            field=models.CharField(default='Join Us', help_text='Members grid call-to-action button text', max_length=200),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='members_grid_cta_url',
            field=models.CharField(blank=True, default='#', help_text='Members grid call-to-action button URL', max_length=500),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='show_members_grid_cta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='show_who_we_are_cta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='who_we_are_cta_text',
            field=models.CharField(default='Join Us', help_text='Who We Are call-to-action button text', max_length=200),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='who_we_are_cta_url',
            field=models.CharField(blank=True, default='#', help_text='Who We Are call-to-action button URL', max_length=500),
        ),
    ]
