# Generated by Django 5.2.12 on 2026-03-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_remove_ourmemberspagesettings_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='bottom_carousel_bg_color',
            field=models.CharField(default='#212129', max_length=7),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='bottom_carousel_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='header_bg_color',
            field=models.CharField(default='#b8f0ed', max_length=7),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='header_text_color',
            field=models.CharField(default='#212129', max_length=7),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='members_grid_bg_color',
            field=models.CharField(default='#f0f0f1', max_length=7),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='members_grid_text_color',
            field=models.CharField(default='#212129', max_length=7),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='top_carousel_bg_color',
            field=models.CharField(default='#a5bfff', max_length=7),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='top_carousel_text_color',
            field=models.CharField(default='#212129', max_length=7),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='who_we_are_bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='ourmemberspagesettings',
            name='who_we_are_text_color',
            field=models.CharField(default='#212129', max_length=7),
        ),
    ]
