# Generated by Django 5.2.12 on 2026-03-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_ourmemberspagesettings_bottom_carousel_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersHeaderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our members.', help_text='Main hero heading', max_length=500)),
                ('bg_color', models.CharField(default='#b8f0ed', max_length=7)),
                ('text_color', models.CharField(default='#212129', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembersInstitutionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='OJC Members.', help_text='Members list section heading', max_length=200)),
                ('bg_color', models.CharField(default='#f0f0f1', max_length=7)),
                ('text_color', models.CharField(default='#212129', max_length=7)),
                ('show_cta', models.BooleanField(default=True)),
                ('cta_text', models.CharField(default='Join Us', max_length=200)),
                ('cta_url', models.CharField(blank=True, default='#', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonCarouselBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(default='#a5bfff', max_length=7)),
                ('text_color', models.CharField(default='#212129', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAreBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_heading', models.CharField(default='Who we are.', help_text='Content section heading', max_length=200)),
                ('circle_1_title', models.CharField(default='We are Academics.', max_length=200)),
                ('circle_1_body', models.TextField(blank=True)),
                ('circle_2_title', models.CharField(default='We are Librarians.', max_length=200)),
                ('circle_2_body', models.TextField(blank=True)),
                ('circle_3_title', models.CharField(default='We are Publishers.', max_length=200)),
                ('circle_3_body', models.TextField(blank=True)),
                ('bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#212129', max_length=7)),
                ('show_cta', models.BooleanField(default=True)),
                ('cta_text', models.CharField(default='Join Us', max_length=200)),
                ('cta_url', models.CharField(blank=True, default='#', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='cms.membersinstitutionsblock')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MembersPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('members_header', 'Members Header'), ('who_we_are', 'Who We Are'), ('person_carousel', 'Person Carousel'), ('members_institutions', 'Members Institutions')], max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.ourmemberspagesettings')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PersonCarouselQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Quote image', upload_to='our_members/carousel/')),
                ('quote_text', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='cms.personcarouselblock')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
