# Generated by Django 5.2.12 on 2026-03-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_page_cms_page_is_publ_f38a87_idx_en_and_more'),
        ('cms', '0039_remove_ourmembersbottomquote_page_and_more'),
    ]

    operations = [
    ]
