# Generated by Django 5.2.12 on 2026-03-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_remove_ourmembersbottomquote_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcarouselblock',
            name='bullet_active_color',
            field=models.CharField(default='#000000', help_text='Carousel dot colour (selected)', max_length=7),
        ),
        migrations.AddField(
            model_name='personcarouselblock',
            name='bullet_color',
            field=models.CharField(default='#999999', help_text='Carousel dot colour (unselected)', max_length=7),
        ),
    ]
