# Generated by Django 5.2.12 on 2026-03-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_merge_20260323_1535'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='page',
            name='cms_page_is_publ_f38a87_idx-en',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='cms_page_is_publ_f38a87_idx-fr',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='cms_page_is_publ_f38a87_idx-de',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='cms_page_is_publ_f38a87_idx-es',
        ),
        migrations.AddField(
            model_name='personcarouselblock',
            name='bullet_active_color',
            field=models.CharField(default='#000000', help_text='Carousel dot colour (selected)', max_length=7),
        ),
        migrations.AddField(
            model_name='personcarouselblock',
            name='bullet_color',
            field=models.CharField(default='#999999', help_text='Carousel dot colour (unselected)', max_length=7),
        ),
    ]
