# Generated by Django 5.2.12 on 2026-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0047_remove_ourmemberspagesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeAccessJournalsBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heading",
                    models.CharField(
                        default="Free access to hundreds of the world’s leading academic journals.",
                        max_length=500,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="blocks/free_access/"
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        default="A modern library representing free access to academic journals",
                        max_length=255,
                    ),
                ),
                ("show_cta", models.BooleanField(default=True)),
                (
                    "cta_text",
                    models.CharField(default="Speak to us", max_length=100),
                ),
                (
                    "cta_url",
                    models.CharField(default="/our-team/", max_length=500),
                ),
                (
                    "bg_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "text_color",
                    models.CharField(default="#212129", max_length=7),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManifestoHeroBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heading",
                    models.CharField(
                        default="OJC is leading a growing academic movement.",
                        help_text="Main hero heading",
                        max_length=500,
                    ),
                ),
                (
                    "sub_heading",
                    models.TextField(
                        blank=True,
                        default="Our mission is to build a sustainable future for academic journals by challenging the profit-making models of global corporate publishing and data systems.",
                        help_text="Hero sub-heading text",
                    ),
                ),
                (
                    "hero_image_alt",
                    models.CharField(
                        default="A person contemplating the future of academic publishing",
                        help_text="Alt text for the hero image",
                        max_length=255,
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(default="#71f7f2", max_length=7),
                ),
                (
                    "text_color",
                    models.CharField(default="#212129", max_length=7),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManifestoOrganiseBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organise_heading",
                    models.CharField(
                        default="To do this, we must organise.", max_length=500
                    ),
                ),
                ("organise_body", models.TextField(blank=True)),
                (
                    "achievable_heading",
                    models.CharField(
                        default="Our task is ambitious, yet achievable.",
                        max_length=500,
                    ),
                ),
                ("achievable_body", models.TextField(blank=True)),
                ("show_cta", models.BooleanField(default=True)),
                (
                    "cta_text",
                    models.CharField(default="It starts here", max_length=100),
                ),
                (
                    "cta_url",
                    models.CharField(default="/our-team/", max_length=500),
                ),
                (
                    "bg_color",
                    models.CharField(default="#a5bfff", max_length=7),
                ),
                (
                    "text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManifestoTextBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(blank=True)),
                (
                    "bg_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "text_color",
                    models.CharField(default="#212129", max_length=7),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
