# Generated by Django 5.2.12 on 2026-03-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0049_seed_manifesto_block_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeaccessjournalsblock',
            name='cta_bg_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='freeaccessjournalsblock',
            name='cta_hover_bg_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='freeaccessjournalsblock',
            name='cta_hover_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='freeaccessjournalsblock',
            name='cta_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='manifestoorganiseblock',
            name='cta_bg_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='manifestoorganiseblock',
            name='cta_hover_bg_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='manifestoorganiseblock',
            name='cta_hover_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='manifestoorganiseblock',
            name='cta_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
