# Generated by Django 5.2.12 on 2026-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_freeaccessjournalsblock_cta_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestoorganiseblock',
            name='achievable_body',
            field=models.TextField(blank=True, default='<p>We want a world where academic research is available to all, with no author fees and no paywalls. Working together with librarians, funders and policymakers, academics and researchers can co-design an exit ramp from this commercial stranglehold.</p><p>This collaboration is what led to the launch of the Open Journals Collective. By building a strong collective network, we protect bibliodiversity and build resilience against a ravaging industry. If not now, perhaps never at all (just kidding).</p>'),
        ),
        migrations.AlterField(
            model_name='manifestoorganiseblock',
            name='organise_body',
            field=models.TextField(blank=True, default='<p>Responding to their own historical moment of capitalist crisis, Marx and Engels wrote in The Communist Manifesto: ‘Workers of the world unite; you have nothing to lose but your chains’. Breaking society up into two great hostile camps, into two great classes directly facing each other: bourgeoisie and proletariat.</p><p>Almost 180 years after this manifesto was written, we find ourselves again at a significant moment of capitalist crisis in academic journals publishing. Our lives are closely drawn with two great classes: directly facing each other. Corporate middle-men publishers like Elsevier, RELX, Wiley, Springer Nature, Taylor &amp; Francis and others continue to extract monopoly profits for their shareholders. Directly facing them is the international academic labour of academics who give these publishers their research while their library colleagues have to find a way to bear the crippling costs of buying this research back.</p><p>The crisis in journals publishing cannot go on any longer. The commodification of the higher education sector simply won’t allow it.</p>'),
        ),
    ]
