# Generated by Django 5.2.12 on 2026-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0051_alter_manifestoorganiseblock_achievable_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestoheroblock',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image (550×526). Will be resized/cropped if needed.', upload_to='blocks/hero/'),
        ),
    ]
