# Generated by Django 5.2.12 on 2026-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_manifestoheroblock_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersheaderblock',
            name='bg_color',
            field=models.CharField(default='#71f7f2', max_length=7),
        ),
    ]
