# Generated by Django 5.2.12 on 2026-03-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0053_alter_membersheaderblock_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoweareblock',
            name='circle_1_body',
            field=models.TextField(blank=True, default='<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit.</p>'),
        ),
        migrations.AlterField(
            model_name='whoweareblock',
            name='circle_2_body',
            field=models.TextField(blank=True, default='<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit.</p>'),
        ),
        migrations.AlterField(
            model_name='whoweareblock',
            name='circle_3_body',
            field=models.TextField(blank=True, default='<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit.</p>'),
        ),
    ]
