# Generated by Django 5.2.12 on 2026-03-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0054_alter_whoweareblock_circle_1_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManifestoPageSettings',
        ),
    ]
