# Generated by Django 5.2.12 on 2026-03-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0055_delete_manifestopagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalFundingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Journal Funding.', max_length=255)),
                ('body', models.TextField(blank=True)),
                ('upper_image', models.ImageField(blank=True, upload_to='blocks/journal_funding/')),
                ('upper_image_alt', models.CharField(default='Academic collaboration in a meeting room', max_length=255)),
                ('lower_image', models.ImageField(blank=True, upload_to='blocks/journal_funding/')),
                ('lower_image_alt', models.CharField(default='Open access academic journals supported by OJC', max_length=255)),
                ('bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#212129', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OJCModelBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='The OJC Model.', max_length=255)),
                ('body', models.TextField(blank=True)),
                ('collections_label', models.TextField(blank=True)),
                ('collection_1_number', models.CharField(default='01', max_length=10)),
                ('collection_1_title', models.CharField(default='The Multidisciplinary Collection', max_length=255)),
                ('collection_1_link_text', models.CharField(default='BROWSE JOURNALS', max_length=100)),
                ('collection_1_link_url', models.CharField(blank=True, max_length=500)),
                ('collection_2_number', models.CharField(default='02', max_length=10)),
                ('collection_2_title', models.CharField(default='The Arts, Humanities & Social Sciences Collection.', max_length=255)),
                ('collection_2_link_text', models.CharField(default='BROWSE JOURNALS', max_length=100)),
                ('collection_2_link_url', models.CharField(blank=True, max_length=500)),
                ('collection_3_number', models.CharField(default='03', max_length=10)),
                ('collection_3_title', models.CharField(default='The Science, Engineering, Technology & Maths Collection.', max_length=255)),
                ('collection_3_link_text', models.CharField(default='BROWSE JOURNALS', max_length=100)),
                ('collection_3_link_url', models.CharField(blank=True, max_length=500)),
                ('circle_bg_color', models.CharField(default='#71f7f2', max_length=7)),
                ('circle_text_color', models.CharField(default='#212129', max_length=7)),
                ('bg_color', models.CharField(default='#e8e8e8', max_length=7)),
                ('text_color', models.CharField(default='#212129', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurModelHeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.TextField(default='By joining OJC, libraries support the long-term sustainability of non-profit, university-based <span class="highlight">journals.</span>', help_text='Hero heading — may contain <span> for highlights')),
                ('hero_image', models.ImageField(blank=True, help_text='Hero image (970x400). Will be resized/cropped if needed.', upload_to='blocks/our_model_hero/')),
                ('hero_image_alt', models.CharField(default='A researcher browsing books in a library', help_text='Alt text for the hero image', max_length=255)),
                ('circle_color', models.CharField(default='#71f7f2', max_length=7)),
                ('bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#212129', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueDistributionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Journal Funding &\nRevenue Distribution.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('callout', models.TextField(blank=True)),
                ('bg_color', models.CharField(default='#e8e8e8', max_length=7)),
                ('text_color', models.CharField(default='#212129', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextImageCTABlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Title here.', max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/text_image_cta/')),
                ('image_alt', models.CharField(default='A collection of academic journal covers from OJC publishers', max_length=255)),
                ('show_cta', models.BooleanField(default=True)),
                ('cta_text', models.CharField(default='Join the movement', max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('cta_bg_color', models.CharField(default='#000000', max_length=7)),
                ('cta_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('cta_hover_bg_color', models.CharField(default='#000000', max_length=7)),
                ('cta_hover_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#212129', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenuePackageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('colour_preset', models.CharField(choices=[('pink', 'Pink'), ('green', 'Green'), ('blue', 'Blue'), ('custom', 'Custom')], default='pink', max_length=10)),
                ('custom_header_bg', models.CharField(blank=True, max_length=7)),
                ('custom_row_bg', models.CharField(blank=True, max_length=7)),
                ('custom_text_colour', models.CharField(blank=True, max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_tables', to='cms.revenuedistributionblock')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RevenuePackageRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='cms.revenuepackagetable')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RevenueTableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='cms.revenuedistributionblock')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RevenuePackageCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='cms.revenuepackagerow')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.revenuetablecolumn')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('row', 'column'), name='unique_revenue_cell_per_row_column')],
            },
        ),
    ]
