# Generated by Django 5.2.12 on 2026-03-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0057_seed_our_model_block_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenuedistributionblock",
            name="callout",
            field=models.TextField(
                blank=True,
                default="We will provide documentation, training events, and regular community meet-ups for OJC members.",
            ),
        ),
        migrations.AlterField(
            model_name="revenuedistributionblock",
            name="description",
            field=models.TextField(
                blank=True,
                default="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
            ),
        ),
    ]
