# Generated by Django 5.2.12 on 2026-03-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0058_alter_revenuedistributionblock_callout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenuedistributionblock",
            name="heading",
            field=models.CharField(
                default="Journal Funding & \nRevenue Distribution.", max_length=255
            ),
        ),
    ]
