# Generated by Django 5.2.12 on 2026-03-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0060_fix_revenue_heading_space"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ourmodelpackagerow",
            name="table",
        ),
        migrations.RemoveField(
            model_name="ourmodelpackagetable",
            name="settings",
        ),
        migrations.RemoveField(
            model_name="ourmodeltablecolumn",
            name="settings",
        ),
        migrations.DeleteModel(
            name="OurModelPackageCell",
        ),
        migrations.DeleteModel(
            name="OurModelPackageRow",
        ),
        migrations.DeleteModel(
            name="OurModelPackageTable",
        ),
        migrations.DeleteModel(
            name="OurModelPageSettings",
        ),
        migrations.DeleteModel(
            name="OurModelTableColumn",
        ),
    ]
