# Generated by Django 5.2.12 on 2026-03-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0061_remove_ourmodelpackagerow_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleListBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Board Members.", max_length=255)),
                ("bg_color", models.CharField(default="#ffffff", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
                ("card_bg_color", models.CharField(default="#71f7f2", max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PeopleListPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("linkedin_url", models.CharField(blank=True, max_length=500)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Person photo (will be cropped to 600x400)",
                        upload_to="blocks/people_list/",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="cms.peoplelistblock",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
