# Generated by Django 5.2.12 on 2026-03-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0065_update_ojc_boards_with_images"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoardMember",
        ),
        migrations.DeleteModel(
            name="BoardSection",
        ),
    ]
