# Generated by Django 5.2.12 on 2026-03-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0069_restore_our_team_images"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamMember",
        ),
        migrations.DeleteModel(
            name="TeamSection",
        ),
    ]
