# Generated by Django 5.2.12 on 2026-03-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0070_remove_teamsection_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationCarouselBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bg_color", models.CharField(default="#a5bfff", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
                (
                    "bullet_color",
                    models.CharField(
                        default="#999999",
                        help_text="Carousel dot colour (unselected)",
                        max_length=7,
                    ),
                ),
                (
                    "bullet_active_color",
                    models.CharField(
                        default="#212129",
                        help_text="Carousel dot colour (selected)",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StatisticsBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stat_1_value", models.CharField(default="6", max_length=50)),
                ("stat_1_text", models.TextField(blank=True)),
                ("stat_2_value", models.CharField(default="60%", max_length=50)),
                ("stat_2_text", models.TextField(blank=True)),
                ("stat_3_value", models.CharField(default="3m", max_length=50)),
                ("stat_3_text", models.TextField(blank=True)),
                ("stat_4_value", models.CharField(default="300k", max_length=50)),
                ("stat_4_text", models.TextField(blank=True)),
                ("bg_color", models.CharField(default="#ffffff", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
                ("border_color", models.CharField(default="#a5bfff", max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TwoColumnContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section_title",
                    models.CharField(default="About us.", max_length=200),
                ),
                (
                    "col_1_title",
                    models.CharField(default="Our vision.", max_length=200),
                ),
                ("col_1_body", models.TextField(blank=True)),
                (
                    "col_2_title",
                    models.CharField(default="Our Mission.", max_length=200),
                ),
                ("col_2_body", models.TextField(blank=True)),
                ("bg_color", models.CharField(default="#ffffff", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WideHeaderCirclesBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heading",
                    models.CharField(
                        default="Our mission is lorem ipsum dolor sit amet, consectetur ips remit et.",
                        help_text="Main hero heading",
                        max_length=500,
                    ),
                ),
                (
                    "sub_heading",
                    models.TextField(
                        blank=True, default="", help_text="Hero sub-heading text"
                    ),
                ),
                ("bg_color", models.CharField(default="#71f7f2", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
                ("circle_color", models.CharField(default="#ffffff", max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrgCarouselQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo image",
                        upload_to="blocks/org_carousel/",
                    ),
                ),
                ("quote_text", models.TextField()),
                ("author_name", models.CharField(max_length=255)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="cms.organizationcarouselblock",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
