# Generated by Django 5.2.12 on 2026-03-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0072_seed_about_us_block_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutusquote",
            name="page",
        ),
        migrations.DeleteModel(
            name="AboutUsPageSettings",
        ),
        migrations.DeleteModel(
            name="AboutUsQuote",
        ),
    ]
