# Generated by Django 5.2.12 on 2026-03-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0073_remove_aboutuspagesettings_and_aboutusquote"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intro_text",
                    models.TextField(
                        default="If you'd like to get in touch with a member of our team, please use the contact form."
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(default="noreply@example.com", max_length=254),
                ),
                ("bg_color", models.CharField(default="#f0f0f1", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactFormRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="cms.contactformblock",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
