# Generated by Django 5.2.12 on 2026-03-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0075_add_contact_form_to_our_team_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactrecipient",
            name="settings",
        ),
        migrations.DeleteModel(
            name="ContactFormSettings",
        ),
        migrations.DeleteModel(
            name="ContactRecipient",
        ),
    ]
