# Generated by Django 5.2.12 on 2026-03-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0076_remove_contactrecipient_settings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureCardBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="Feature title.", max_length=255)),
                ("text", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="blocks/feature_card/"),
                ),
                ("image_alt", models.CharField(blank=True, max_length=255)),
                ("number", models.CharField(default="01", max_length=5)),
                ("cta_text", models.CharField(default="LEARN MORE", max_length=100)),
                ("cta_url", models.CharField(blank=True, max_length=500)),
                ("cta_bg_color", models.CharField(default="#212129", max_length=7)),
                ("cta_text_color", models.CharField(default="#ffffff", max_length=7)),
                (
                    "cta_hover_bg_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                (
                    "cta_hover_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                ("card_bg_color", models.CharField(default="#a5bfff", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandingHeroBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heading",
                    models.TextField(
                        default="We're a collective of libraries and university publishers reshaping academic research.",
                        help_text="Main hero heading",
                    ),
                ),
                (
                    "sub_heading",
                    models.TextField(
                        blank=True,
                        default="Add a bit more info here, means we can be a bit more punchy to the point above and adipiscing elit, sed do a cursus semper.",
                        help_text="Hero sub-heading text",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(default="JOIN THE MOVEMENT", max_length=100),
                ),
                ("cta_url", models.CharField(blank=True, max_length=500)),
                ("cta_bg_color", models.CharField(default="#212129", max_length=7)),
                ("cta_text_color", models.CharField(default="#ffffff", max_length=7)),
                (
                    "cta_hover_bg_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                (
                    "cta_hover_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                ("bg_color", models.CharField(default="#ffffff", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
                ("circle_color", models.CharField(default="#FFDE59", max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandingStatsBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fundraising_target", models.PositiveIntegerField(default=14000)),
                ("amount_raised", models.PositiveIntegerField(default=11500)),
                ("description", models.TextField(blank=True)),
                (
                    "button_1_text",
                    models.CharField(default="JOIN THE MOVEMENT", max_length=100),
                ),
                ("button_1_url", models.CharField(blank=True, max_length=500)),
                (
                    "button_1_bg_color",
                    models.CharField(default="#212129", max_length=7),
                ),
                (
                    "button_1_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "button_1_hover_bg_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                (
                    "button_1_hover_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                ("button_2_text", models.CharField(default="SHARE", max_length=100)),
                ("button_2_url", models.CharField(blank=True, max_length=500)),
                (
                    "button_2_bg_color",
                    models.CharField(default="#212129", max_length=7),
                ),
                (
                    "button_2_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "button_2_hover_bg_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                (
                    "button_2_hover_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                ("bg_color", models.CharField(default="#FFDE59", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
                ("ring_color", models.CharField(default="#ffffff", max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="blockpage",
            name="is_landing_page",
            field=models.BooleanField(
                default=False,
                help_text="Serve this page at / instead of the old landing page",
            ),
        ),
    ]
