# Generated by Django 5.2.12 on 2026-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0078_seed_landing_page_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureCardsBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card_1_title",
                    models.CharField(default="Feature title.", max_length=255),
                ),
                ("card_1_text", models.TextField(blank=True)),
                (
                    "card_1_image",
                    models.ImageField(blank=True, upload_to="blocks/feature_cards/"),
                ),
                ("card_1_image_alt", models.CharField(blank=True, max_length=255)),
                ("card_1_number", models.CharField(default="01", max_length=5)),
                (
                    "card_1_cta_text",
                    models.CharField(default="LEARN MORE", max_length=100),
                ),
                ("card_1_cta_url", models.CharField(blank=True, max_length=500)),
                ("card_1_bg_color", models.CharField(default="#a5bfff", max_length=7)),
                (
                    "card_2_title",
                    models.CharField(default="Feature title.", max_length=255),
                ),
                ("card_2_text", models.TextField(blank=True)),
                (
                    "card_2_image",
                    models.ImageField(blank=True, upload_to="blocks/feature_cards/"),
                ),
                ("card_2_image_alt", models.CharField(blank=True, max_length=255)),
                ("card_2_number", models.CharField(default="02", max_length=5)),
                (
                    "card_2_cta_text",
                    models.CharField(default="LEARN MORE", max_length=100),
                ),
                ("card_2_cta_url", models.CharField(blank=True, max_length=500)),
                ("card_2_bg_color", models.CharField(default="#78f2c1", max_length=7)),
                (
                    "card_3_title",
                    models.CharField(default="Feature title.", max_length=255),
                ),
                ("card_3_text", models.TextField(blank=True)),
                (
                    "card_3_image",
                    models.ImageField(blank=True, upload_to="blocks/feature_cards/"),
                ),
                ("card_3_image_alt", models.CharField(blank=True, max_length=255)),
                ("card_3_number", models.CharField(default="03", max_length=5)),
                (
                    "card_3_cta_text",
                    models.CharField(default="LEARN MORE", max_length=100),
                ),
                ("card_3_cta_url", models.CharField(blank=True, max_length=500)),
                ("card_3_bg_color", models.CharField(default="#ffd4f7", max_length=7)),
                ("text_color", models.CharField(default="#212129", max_length=7)),
                ("cta_bg_color", models.CharField(default="#212129", max_length=7)),
                ("cta_text_color", models.CharField(default="#ffffff", max_length=7)),
                (
                    "cta_hover_bg_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                (
                    "cta_hover_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="FeatureCardBlock",
        ),
    ]
