# Generated by Django 5.2.12 on 2026-03-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0080_update_landing_template_feature_cards"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LandingPageSettings",
        ),
    ]
