# Generated by Django 4.2.25 on 2025-10-27 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Name of the imported file', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Import status', max_length=20)),
                ('records_processed', models.IntegerField(default=0, help_text='Number of records processed')),
                ('records_created', models.IntegerField(default=0, help_text='Number of new records created')),
                ('records_updated', models.IntegerField(default=0, help_text='Number of existing records updated')),
                ('records_failed', models.IntegerField(default=0, help_text='Number of records that failed to import')),
                ('error_log', models.TextField(blank=True, help_text='Detailed error messages and warnings')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Language name', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text="ISO language code (e.g., 'en', 'fr', 'es')", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the publisher organization', max_length=255, unique=True)),
                ('website', models.URLField(blank=True, help_text="Publisher's website URL", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject or discipline name', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full journal title', max_length=500, unique=True)),
                ('year_established', models.CharField(blank=True, help_text='Year established or original zombie designation', max_length=100)),
                ('journal_owner', models.CharField(blank=True, help_text='Organization or entity that owns the journal', max_length=255)),
                ('package_band', models.CharField(blank=True, choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4')], help_text='Package and band classification', max_length=10)),
                ('cost_gbp', models.DecimalField(blank=True, decimal_places=2, help_text='Cost in British Pounds', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('normalized_articles', models.DecimalField(blank=True, decimal_places=2, help_text='Normalized number of articles', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('journal_url', models.URLField(blank=True, help_text='Link to journal website')),
                ('publisher_url', models.URLField(blank=True, help_text='Link to publisher website')),
                ('issn', models.CharField(blank=True, help_text='International Standard Serial Number', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Journal description and scope')),
                ('in_doaj', models.BooleanField(default=False, help_text='Whether journal is listed in Directory of Open Access Journals')),
                ('in_scopus', models.BooleanField(default=False, help_text='Whether journal is indexed in Scopus')),
                ('wos_impact_factor', models.DecimalField(blank=True, decimal_places=2, help_text='Web of Science Impact Factor', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('archive_available_diamond_oa', models.TextField(blank=True, help_text='Details about diamond OA archive availability')),
                ('archive_years', models.IntegerField(blank=True, help_text='Number of years of archive available', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('usps', models.TextField(blank=True, help_text='Unique selling points to note', verbose_name='USPs')),
                ('licensing', models.CharField(blank=True, choices=[('CC BY', 'CC BY'), ('CC BY-NC', 'CC BY-NC'), ('CC BY-NC-SA', 'CC BY-NC-SA'), ('CC BY-NC-ND', 'CC BY-NC-ND'), ('CC BY-SA', 'CC BY-SA'), ('CC BY-ND', 'CC BY-ND')], help_text='Creative Commons or other license type', max_length=50)),
                ('archiving_services', models.TextField(blank=True, help_text='Archiving services (CLOCKSS, LOCKSS, PKP PN, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('languages', models.ManyToManyField(blank=True, help_text='Languages in which the journal publishes', related_name='journals', to='journals.language')),
                ('publisher', models.ForeignKey(help_text='Publishing organization', on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='journals.publisher')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Academic subjects covered by the journal', related_name='journals', to='journals.subject')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['publisher', 'package_band'], name='journals_jo_publish_03f116_idx'), models.Index(fields=['cost_gbp'], name='journals_jo_cost_gb_ce4f8c_idx'), models.Index(fields=['in_doaj'], name='journals_jo_in_doaj_01889f_idx')],
            },
        ),
    ]
