# Generated by Django 4.2.25 on 2025-10-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20251027_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Package band code (e.g., C1, C2)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Descriptive name of the package band', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package Band',
                'verbose_name_plural': 'Package Bands',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='journal',
            name='package_band',
            field=models.ForeignKey(blank=True, help_text='Package and band classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='journals.packageband'),
        ),
    ]
