# Generated by Django 4.2.25 on 2025-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_packageband_remove_journal_journal_title_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='licensing',
            field=models.CharField(blank=True, choices=[('CC BY', 'CC BY'), ('CC BY-NC', 'CC BY-NC'), ('CC BY-NC-SA', 'CC BY-NC-SA'), ('CC BY-NC-ND', 'CC BY-NC-ND'), ('CC BY-SA', 'CC BY-SA'), ('CC BY-ND', 'CC BY-ND')], help_text='Creative Commons or other license type', max_length=100),
        ),
    ]
