# Generated by Django 4.2.25 on 2025-11-24 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_remove_journal_journal_title_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
