# Generated by Django 4.2.25 on 2025-12-09 10:36

from django.db import migrations, models
import journals.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_remove_journal_journal_title_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='cover',
            field=models.ImageField(blank=True, help_text='Journal cover image', null=True, upload_to=journals.models.journal_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='journal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
