# Generated by Django 4.2.29 on 2026-03-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_archivingservice_m2m'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journal',
            name='journal_title_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='journal_cost_idx',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='journal_articles_idx',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='journal_impact_idx',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='journal_indexing_idx',
        ),
        migrations.RenameIndex(
            model_name='journal',
            new_name='journals_jo_publish_eb16f4_idx',
            old_name='journal_pub_band_idx',
        ),
        migrations.AlterField(
            model_name='archivingservice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
