# Generated by Django 4.2.29 on 2026-03-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_remove_journal_journal_title_trgm_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journal',
            name='journals_jo_publish_03f116_idx',
        ),
    ]
