# Generated by Django 5.2.12 on 2026-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_remove_journal_journals_jo_publish_03f116_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='cover',
            field=models.ImageField(blank=True, help_text='Journal cover image', null=True, upload_to='journal_covers/'),
        ),
    ]
