# Generated by Django 5.2.12 on 2026-05-07 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_journal_cover_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='financial_information',
            field=models.TextField(blank=True, help_text='Funding model, sponsorships, or other financial notes'),
        ),
        migrations.AddField(
            model_name='journal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
