# Generated by Django 5.2.12 on 2026-06-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_journal_financial_information_journal_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Platform name', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='platform',
            field=models.ForeignKey(blank=True, help_text='Publishing platform the journal runs on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='journals.platform'),
        ),
    ]
