"""
Django settings for astrometrics project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import structlog
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-7)quvmg#txg+_pg87x7&ulbcuj#@%5f=7@etu_zx2d1-!8)ylj",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(
    ","
)


# Application definition

INSTALLED_APPS = [
    # modeltranslation must precede django.contrib.admin
    "modeltranslation",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # PostgreSQL specific features (REQUIRED for full-text search)
    "django.contrib.postgres",
    # Third-party
    "django_extensions",
    "django_structlog",
    "tinymce",
    # Project apps
    "journals",
    "cms",
    "manager",
    "portal",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "astrometrics.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cms.context_processors.footer_settings",
                "cms.context_processors.header_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "astrometrics.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_config = dj_database_url.config(
    default=os.environ.get("DATABASE_URL", ""),
    conn_max_age=600,
)
_db_config["OPTIONS"] = {
    "connect_timeout": 10,
    "options": "-c statement_timeout=30000",
}
DATABASES = {"default": _db_config}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

_VALIDATORS_PREFIX = "django.contrib.auth.password_validation"
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": f"{_VALIDATORS_PREFIX}.UserAttributeSimilarityValidator"},
    {"NAME": f"{_VALIDATORS_PREFIX}.MinimumLengthValidator"},
    {"NAME": f"{_VALIDATORS_PREFIX}.CommonPasswordValidator"},
    {"NAME": f"{_VALIDATORS_PREFIX}.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("fr", "French"),
    ("de", "German"),
    ("es", "Spanish"),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"  # Add the leading slash!

# For production - where collectstatic puts files
STATIC_ROOT = BASE_DIR / "staticfiles"  # Change this!

# For development - where your source files are
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Add this line!
]

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Email
# Django's email framework supports SMTP, SES, Mailgun, etc. by switching
# the EMAIL_BACKEND setting.  In debug mode we log to the console.
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", "noreply@example.com"
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

PAGINATE_BY = 25

# TinyMCE rich-text editor
# Toolbar is scoped to match the Bleach allowlist in cms/models.py so
# editors don't see buttons whose output will be stripped on save.
# valid_elements is intentionally omitted — restricting it collapses
# pasted content (Word wraps everything in divs/spans that aren't in the
# schema). Bleach handles final sanitisation on save instead.
TINYMCE_DEFAULT_CONFIG = {
    "height": 500,
    "menubar": False,
    "plugins": "lists link image table code fullscreen wordcount",
    "toolbar": (
        "undo redo | blocks | "
        "bold italic underline | "
        "link image | "
        "bullist numlist | "
        "blockquote hr | "
        "table | "
        "sub sup | "
        "code | fullscreen"
    ),
    # Content CSS: load the site's own fonts and styles so the editor
    # previews content as it will appear on the front end.
    "content_css": [
        "https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap",
        "/static/css/normalize.min.css",
        "/static/css/font.css",
        "/static/css/app.css",
        "/static/css/news.css",
    ],
    # Scope the editor body inside the same class used on the front end
    # so all rich-text styles (tables, lists, blockquotes etc.) apply.
    "body_class": "news-detail-body__inner",
    "content_style": "body.news-detail-body__inner { padding: 16px 24px; }",
    # Paste cleanup — setup is eval'd into a real JS function by
    # django-tinymce's init_tinymce.js. DOM-based so we can surgically
    # strip junk without destroying semantic structure.
    "setup": """function(editor) {
  var BLOCK_TAGS = ['P','H1','H2','H3','H4','H5','H6','LI','UL','OL',
                    'BLOCKQUOTE','TABLE','THEAD','TBODY','TR','TD','TH'];
  var JUNK_ATTRS = ['id','dir','aria-level','role','lang','class'];
  var KEEP_STYLE_RE = /^(font-weight|font-style|text-decoration)$/i;

  function cleanEl(el) {
    JUNK_ATTRS.forEach(function(a) { el.removeAttribute(a); });
    if (BLOCK_TAGS.indexOf(el.tagName) !== -1) {
      el.removeAttribute('style');
    } else {
      var raw = el.getAttribute('style') || '';
      var kept = raw.split(';').filter(function(rule) {
        var prop = (rule.split(':')[0] || '').trim();
        return prop && KEEP_STYLE_RE.test(prop);
      }).join(';');
      kept ? el.setAttribute('style', kept) : el.removeAttribute('style');
    }
  }

  editor.on('PastePreProcess', function(evt) {
    var d = document.createElement('div');
    d.innerHTML = evt.content;
    d.querySelectorAll('font').forEach(function(el) {
      var frag = document.createDocumentFragment();
      while (el.firstChild) frag.appendChild(el.firstChild);
      if (el.parentNode) el.parentNode.replaceChild(frag, el);
    });
    d.querySelectorAll('*').forEach(cleanEl);
    evt.content = d.innerHTML;
  });
}""",
    # Image upload
    "images_upload_url": "/manager/cms/image-upload/",
    "images_upload_credentials": True,
    "automatic_uploads": True,
    "file_picker_types": "image",
    "image_caption": False,
}

# Logging configuration

_common_processors = [
    structlog.contextvars.merge_contextvars,
    structlog.stdlib.add_logger_name,
    structlog.stdlib.add_log_level,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.TimeStamper(fmt="iso"),
    structlog.processors.StackInfoRenderer(),
    structlog.processors.UnicodeDecoder(),
]

_renderer = (
    structlog.dev.ConsoleRenderer()
    if DEBUG
    else structlog.processors.JSONRenderer()
)

structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        *_common_processors,
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

# Django Debug Toolbar (development only)
if DEBUG:
    import socket

    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = ["127.0.0.1"]
    # Detect Docker gateway IP so the toolbar shows inside containers
    try:
        _hostname, _aliases, _ips = socket.gethostbyname_ex(
            socket.gethostname()
        )
        INTERNAL_IPS += [ip[: ip.rfind(".")] + ".1" for ip in _ips]
    except OSError:
        pass

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "structured": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processors": [
                structlog.stdlib.ProcessorFormatter.remove_processors_meta,
                _renderer,
            ],
            "foreign_pre_chain": _common_processors,
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "structured",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        "django": {
            "level": "INFO",
        },
        "django.server": {
            "level": "WARNING",
        },
        "django_structlog": {
            "level": "INFO",
        },
        "werkzeug": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
