"""
Django settings for astrometrics project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import structlog

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-7)quvmg#txg+_pg87x7&ulbcuj#@%5f=7@etu_zx2d1-!8)ylj",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(
    ","
)


# Application definition

INSTALLED_APPS = [
    # modeltranslation must precede django.contrib.admin
    "modeltranslation",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # PostgreSQL specific features (REQUIRED for full-text search)
    "django.contrib.postgres",
    # Third-party
    "django_extensions",
    "django_structlog",
    # Project apps
    "journals",
    "cms",
    "manager",
    "portal",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "astrometrics.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "astrometrics.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_DB_DEFAULT_URL = "postgresql://ajrbyers:legosword@localhost:5432/astrometrics"
_db_config = dj_database_url.config(
    default=os.environ.get("DATABASE_URL", _DB_DEFAULT_URL),
    conn_max_age=600,
)
_db_config["OPTIONS"] = {
    "connect_timeout": 10,
    "options": "-c statement_timeout=30000",
}
DATABASES = {"default": _db_config}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

_VALIDATORS_PREFIX = "django.contrib.auth.password_validation"
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": f"{_VALIDATORS_PREFIX}.UserAttributeSimilarityValidator"},
    {"NAME": f"{_VALIDATORS_PREFIX}.MinimumLengthValidator"},
    {"NAME": f"{_VALIDATORS_PREFIX}.CommonPasswordValidator"},
    {"NAME": f"{_VALIDATORS_PREFIX}.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("fr", "French"),
    ("de", "German"),
    ("es", "Spanish"),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"  # Add the leading slash!

# For production - where collectstatic puts files
STATIC_ROOT = BASE_DIR / "staticfiles"  # Change this!

# For development - where your source files are
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Add this line!
]

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

PAGINATE_BY = 25

# Logging configuration

_common_processors = [
    structlog.contextvars.merge_contextvars,
    structlog.stdlib.add_logger_name,
    structlog.stdlib.add_log_level,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.TimeStamper(fmt="iso"),
    structlog.processors.StackInfoRenderer(),
    structlog.processors.UnicodeDecoder(),
]

_renderer = (
    structlog.dev.ConsoleRenderer()
    if DEBUG
    else structlog.processors.JSONRenderer()
)

structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        *_common_processors,
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "structured": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processors": [
                structlog.stdlib.ProcessorFormatter.remove_processors_meta,
                _renderer,
            ],
            "foreign_pre_chain": _common_processors,
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "structured",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        "django": {
            "level": "INFO",
        },
        "django.server": {
            "level": "WARNING",
        },
        "django_structlog": {
            "level": "INFO",
        },
        "werkzeug": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
